// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace IOApp.CompiledModels
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var folderEntity = FolderEntityEntityType.Create(this);
            var playlistEntity = PlaylistEntityEntityType.Create(this);
            var playlistFileEntity = PlaylistFileEntityEntityType.Create(this);
            var privateEntity = PrivateEntityEntityType.Create(this);
            var recentEntity = RecentEntityEntityType.Create(this);

            PlaylistFileEntityEntityType.CreateForeignKey1(playlistFileEntity, playlistEntity);

            FolderEntityEntityType.CreateAnnotations(folderEntity);
            PlaylistEntityEntityType.CreateAnnotations(playlistEntity);
            PlaylistFileEntityEntityType.CreateAnnotations(playlistFileEntity);
            PrivateEntityEntityType.CreateAnnotations(privateEntity);
            RecentEntityEntityType.CreateAnnotations(recentEntity);

            AddAnnotation("ProductVersion", "8.0.8");
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var folderEntity = FindEntityType("IOApp.Features.FolderEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            folderEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var ioAppFolderEntityTableBase = new TableBase("IOApp.Features.FolderEntity", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "INTEGER", ioAppFolderEntityTableBase);
            ioAppFolderEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", ioAppFolderEntityTableBase);
            ioAppFolderEntityTableBase.Columns.Add("Id", idColumnBase);
            var isSelectedColumnBase = new ColumnBase<ColumnMappingBase>("IsSelected", "INTEGER", ioAppFolderEntityTableBase);
            ioAppFolderEntityTableBase.Columns.Add("IsSelected", isSelectedColumnBase);
            var lastOpenedAtColumnBase = new ColumnBase<ColumnMappingBase>("LastOpenedAt", "INTEGER", ioAppFolderEntityTableBase);
            ioAppFolderEntityTableBase.Columns.Add("LastOpenedAt", lastOpenedAtColumnBase);
            var pathColumnBase = new ColumnBase<ColumnMappingBase>("Path", "TEXT", ioAppFolderEntityTableBase)
            {
                IsNullable = true
            };
            ioAppFolderEntityTableBase.Columns.Add("Path", pathColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "INTEGER", ioAppFolderEntityTableBase);
            ioAppFolderEntityTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            relationalModel.DefaultTables.Add("IOApp.Features.FolderEntity", ioAppFolderEntityTableBase);
            var ioAppFolderEntityMappingBase = new TableMappingBase<ColumnMappingBase>(folderEntity, ioAppFolderEntityTableBase, true);
            ioAppFolderEntityTableBase.AddTypeMapping(ioAppFolderEntityMappingBase, false);
            defaultTableMappings.Add(ioAppFolderEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, folderEntity.FindProperty("Id")!, ioAppFolderEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, folderEntity.FindProperty("CreatedAt")!, ioAppFolderEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isSelectedColumnBase, folderEntity.FindProperty("IsSelected")!, ioAppFolderEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastOpenedAtColumnBase, folderEntity.FindProperty("LastOpenedAt")!, ioAppFolderEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase, folderEntity.FindProperty("Path")!, ioAppFolderEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, folderEntity.FindProperty("UpdatedAt")!, ioAppFolderEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            folderEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var foldersTable = new Table("Folders", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", foldersTable);
            foldersTable.Columns.Add("Id", idColumn);
            var createdAtColumn = new Column("CreatedAt", "INTEGER", foldersTable);
            foldersTable.Columns.Add("CreatedAt", createdAtColumn);
            var isSelectedColumn = new Column("IsSelected", "INTEGER", foldersTable);
            foldersTable.Columns.Add("IsSelected", isSelectedColumn);
            var lastOpenedAtColumn = new Column("LastOpenedAt", "INTEGER", foldersTable);
            foldersTable.Columns.Add("LastOpenedAt", lastOpenedAtColumn);
            var pathColumn = new Column("Path", "TEXT", foldersTable)
            {
                IsNullable = true
            };
            foldersTable.Columns.Add("Path", pathColumn);
            var updatedAtColumn = new Column("UpdatedAt", "INTEGER", foldersTable);
            foldersTable.Columns.Add("UpdatedAt", updatedAtColumn);
            var pK_Folders = new UniqueConstraint("PK_Folders", foldersTable, new[] { idColumn });
            foldersTable.PrimaryKey = pK_Folders;
            var pK_FoldersUc = RelationalModel.GetKey(this,
                "IOApp.Features.FolderEntity",
                new[] { "Id" });
            pK_Folders.MappedKeys.Add(pK_FoldersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FoldersUc).Add(pK_Folders);
            foldersTable.UniqueConstraints.Add("PK_Folders", pK_Folders);
            relationalModel.Tables.Add(("Folders", null), foldersTable);
            var foldersTableMapping = new TableMapping(folderEntity, foldersTable, true);
            foldersTable.AddTypeMapping(foldersTableMapping, false);
            tableMappings.Add(foldersTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, folderEntity.FindProperty("Id")!, foldersTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, folderEntity.FindProperty("CreatedAt")!, foldersTableMapping);
            RelationalModel.CreateColumnMapping(isSelectedColumn, folderEntity.FindProperty("IsSelected")!, foldersTableMapping);
            RelationalModel.CreateColumnMapping(lastOpenedAtColumn, folderEntity.FindProperty("LastOpenedAt")!, foldersTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn, folderEntity.FindProperty("Path")!, foldersTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, folderEntity.FindProperty("UpdatedAt")!, foldersTableMapping);

            var playlistEntity = FindEntityType("IOApp.Features.PlaylistEntity")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            playlistEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var ioAppPlaylistEntityTableBase = new TableBase("IOApp.Features.PlaylistEntity", null, relationalModel);
            var createdAtColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedAt", "INTEGER", ioAppPlaylistEntityTableBase);
            ioAppPlaylistEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase0);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", ioAppPlaylistEntityTableBase)
            {
                IsNullable = true
            };
            ioAppPlaylistEntityTableBase.Columns.Add("Description", descriptionColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", ioAppPlaylistEntityTableBase);
            ioAppPlaylistEntityTableBase.Columns.Add("Id", idColumnBase0);
            var lastOpenedAtColumnBase0 = new ColumnBase<ColumnMappingBase>("LastOpenedAt", "INTEGER", ioAppPlaylistEntityTableBase);
            ioAppPlaylistEntityTableBase.Columns.Add("LastOpenedAt", lastOpenedAtColumnBase0);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", ioAppPlaylistEntityTableBase)
            {
                IsNullable = true
            };
            ioAppPlaylistEntityTableBase.Columns.Add("Name", nameColumnBase);
            var orderColumnBase = new ColumnBase<ColumnMappingBase>("Order", "INTEGER", ioAppPlaylistEntityTableBase);
            ioAppPlaylistEntityTableBase.Columns.Add("Order", orderColumnBase);
            var remarkColumnBase = new ColumnBase<ColumnMappingBase>("Remark", "TEXT", ioAppPlaylistEntityTableBase)
            {
                IsNullable = true
            };
            ioAppPlaylistEntityTableBase.Columns.Add("Remark", remarkColumnBase);
            var updatedAtColumnBase0 = new ColumnBase<ColumnMappingBase>("UpdatedAt", "INTEGER", ioAppPlaylistEntityTableBase);
            ioAppPlaylistEntityTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase0);
            relationalModel.DefaultTables.Add("IOApp.Features.PlaylistEntity", ioAppPlaylistEntityTableBase);
            var ioAppPlaylistEntityMappingBase = new TableMappingBase<ColumnMappingBase>(playlistEntity, ioAppPlaylistEntityTableBase, true);
            ioAppPlaylistEntityTableBase.AddTypeMapping(ioAppPlaylistEntityMappingBase, false);
            defaultTableMappings0.Add(ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, playlistEntity.FindProperty("Id")!, ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase0, playlistEntity.FindProperty("CreatedAt")!, ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, playlistEntity.FindProperty("Description")!, ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastOpenedAtColumnBase0, playlistEntity.FindProperty("LastOpenedAt")!, ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, playlistEntity.FindProperty("Name")!, ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderColumnBase, playlistEntity.FindProperty("Order")!, ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)remarkColumnBase, playlistEntity.FindProperty("Remark")!, ioAppPlaylistEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase0, playlistEntity.FindProperty("UpdatedAt")!, ioAppPlaylistEntityMappingBase);

            var tableMappings0 = new List<TableMapping>();
            playlistEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var playlistsTable = new Table("Playlists", null, relationalModel);
            var idColumn0 = new Column("Id", "INTEGER", playlistsTable);
            playlistsTable.Columns.Add("Id", idColumn0);
            var createdAtColumn0 = new Column("CreatedAt", "INTEGER", playlistsTable);
            playlistsTable.Columns.Add("CreatedAt", createdAtColumn0);
            var descriptionColumn = new Column("Description", "TEXT", playlistsTable)
            {
                IsNullable = true
            };
            playlistsTable.Columns.Add("Description", descriptionColumn);
            var lastOpenedAtColumn0 = new Column("LastOpenedAt", "INTEGER", playlistsTable);
            playlistsTable.Columns.Add("LastOpenedAt", lastOpenedAtColumn0);
            var nameColumn = new Column("Name", "TEXT", playlistsTable)
            {
                IsNullable = true
            };
            playlistsTable.Columns.Add("Name", nameColumn);
            var orderColumn = new Column("Order", "INTEGER", playlistsTable);
            playlistsTable.Columns.Add("Order", orderColumn);
            var remarkColumn = new Column("Remark", "TEXT", playlistsTable)
            {
                IsNullable = true
            };
            playlistsTable.Columns.Add("Remark", remarkColumn);
            var updatedAtColumn0 = new Column("UpdatedAt", "INTEGER", playlistsTable);
            playlistsTable.Columns.Add("UpdatedAt", updatedAtColumn0);
            var pK_Playlists = new UniqueConstraint("PK_Playlists", playlistsTable, new[] { idColumn0 });
            playlistsTable.PrimaryKey = pK_Playlists;
            var pK_PlaylistsUc = RelationalModel.GetKey(this,
                "IOApp.Features.PlaylistEntity",
                new[] { "Id" });
            pK_Playlists.MappedKeys.Add(pK_PlaylistsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_PlaylistsUc).Add(pK_Playlists);
            playlistsTable.UniqueConstraints.Add("PK_Playlists", pK_Playlists);
            relationalModel.Tables.Add(("Playlists", null), playlistsTable);
            var playlistsTableMapping = new TableMapping(playlistEntity, playlistsTable, true);
            playlistsTable.AddTypeMapping(playlistsTableMapping, false);
            tableMappings0.Add(playlistsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, playlistEntity.FindProperty("Id")!, playlistsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn0, playlistEntity.FindProperty("CreatedAt")!, playlistsTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, playlistEntity.FindProperty("Description")!, playlistsTableMapping);
            RelationalModel.CreateColumnMapping(lastOpenedAtColumn0, playlistEntity.FindProperty("LastOpenedAt")!, playlistsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, playlistEntity.FindProperty("Name")!, playlistsTableMapping);
            RelationalModel.CreateColumnMapping(orderColumn, playlistEntity.FindProperty("Order")!, playlistsTableMapping);
            RelationalModel.CreateColumnMapping(remarkColumn, playlistEntity.FindProperty("Remark")!, playlistsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn0, playlistEntity.FindProperty("UpdatedAt")!, playlistsTableMapping);

            var playlistFileEntity = FindEntityType("IOApp.Features.PlaylistFileEntity")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            playlistFileEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var ioAppPlaylistFileEntityTableBase = new TableBase("IOApp.Features.PlaylistFileEntity", null, relationalModel);
            var createdAtColumnBase1 = new ColumnBase<ColumnMappingBase>("CreatedAt", "INTEGER", ioAppPlaylistFileEntityTableBase);
            ioAppPlaylistFileEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase1);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", ioAppPlaylistFileEntityTableBase);
            ioAppPlaylistFileEntityTableBase.Columns.Add("Id", idColumnBase1);
            var lastOpenedAtColumnBase1 = new ColumnBase<ColumnMappingBase>("LastOpenedAt", "INTEGER", ioAppPlaylistFileEntityTableBase);
            ioAppPlaylistFileEntityTableBase.Columns.Add("LastOpenedAt", lastOpenedAtColumnBase1);
            var pathColumnBase0 = new ColumnBase<ColumnMappingBase>("Path", "TEXT", ioAppPlaylistFileEntityTableBase)
            {
                IsNullable = true
            };
            ioAppPlaylistFileEntityTableBase.Columns.Add("Path", pathColumnBase0);
            var playlistIdColumnBase = new ColumnBase<ColumnMappingBase>("PlaylistId", "INTEGER", ioAppPlaylistFileEntityTableBase);
            ioAppPlaylistFileEntityTableBase.Columns.Add("PlaylistId", playlistIdColumnBase);
            var updatedAtColumnBase1 = new ColumnBase<ColumnMappingBase>("UpdatedAt", "INTEGER", ioAppPlaylistFileEntityTableBase);
            ioAppPlaylistFileEntityTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase1);
            relationalModel.DefaultTables.Add("IOApp.Features.PlaylistFileEntity", ioAppPlaylistFileEntityTableBase);
            var ioAppPlaylistFileEntityMappingBase = new TableMappingBase<ColumnMappingBase>(playlistFileEntity, ioAppPlaylistFileEntityTableBase, true);
            ioAppPlaylistFileEntityTableBase.AddTypeMapping(ioAppPlaylistFileEntityMappingBase, false);
            defaultTableMappings1.Add(ioAppPlaylistFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, playlistFileEntity.FindProperty("Id")!, ioAppPlaylistFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase1, playlistFileEntity.FindProperty("CreatedAt")!, ioAppPlaylistFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastOpenedAtColumnBase1, playlistFileEntity.FindProperty("LastOpenedAt")!, ioAppPlaylistFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase0, playlistFileEntity.FindProperty("Path")!, ioAppPlaylistFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)playlistIdColumnBase, playlistFileEntity.FindProperty("PlaylistId")!, ioAppPlaylistFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase1, playlistFileEntity.FindProperty("UpdatedAt")!, ioAppPlaylistFileEntityMappingBase);

            var tableMappings1 = new List<TableMapping>();
            playlistFileEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var playlistFilesTable = new Table("PlaylistFiles", null, relationalModel);
            var idColumn1 = new Column("Id", "INTEGER", playlistFilesTable);
            playlistFilesTable.Columns.Add("Id", idColumn1);
            var createdAtColumn1 = new Column("CreatedAt", "INTEGER", playlistFilesTable);
            playlistFilesTable.Columns.Add("CreatedAt", createdAtColumn1);
            var lastOpenedAtColumn1 = new Column("LastOpenedAt", "INTEGER", playlistFilesTable);
            playlistFilesTable.Columns.Add("LastOpenedAt", lastOpenedAtColumn1);
            var pathColumn0 = new Column("Path", "TEXT", playlistFilesTable)
            {
                IsNullable = true
            };
            playlistFilesTable.Columns.Add("Path", pathColumn0);
            var playlistIdColumn = new Column("PlaylistId", "INTEGER", playlistFilesTable);
            playlistFilesTable.Columns.Add("PlaylistId", playlistIdColumn);
            var updatedAtColumn1 = new Column("UpdatedAt", "INTEGER", playlistFilesTable);
            playlistFilesTable.Columns.Add("UpdatedAt", updatedAtColumn1);
            var pK_PlaylistFiles = new UniqueConstraint("PK_PlaylistFiles", playlistFilesTable, new[] { idColumn1 });
            playlistFilesTable.PrimaryKey = pK_PlaylistFiles;
            var pK_PlaylistFilesUc = RelationalModel.GetKey(this,
                "IOApp.Features.PlaylistFileEntity",
                new[] { "Id" });
            pK_PlaylistFiles.MappedKeys.Add(pK_PlaylistFilesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_PlaylistFilesUc).Add(pK_PlaylistFiles);
            playlistFilesTable.UniqueConstraints.Add("PK_PlaylistFiles", pK_PlaylistFiles);
            var iX_PlaylistFiles_PlaylistId = new TableIndex(
            "IX_PlaylistFiles_PlaylistId", playlistFilesTable, new[] { playlistIdColumn }, false);
            var iX_PlaylistFiles_PlaylistIdIx = RelationalModel.GetIndex(this,
                "IOApp.Features.PlaylistFileEntity",
                new[] { "PlaylistId" });
            iX_PlaylistFiles_PlaylistId.MappedIndexes.Add(iX_PlaylistFiles_PlaylistIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_PlaylistFiles_PlaylistIdIx).Add(iX_PlaylistFiles_PlaylistId);
            playlistFilesTable.Indexes.Add("IX_PlaylistFiles_PlaylistId", iX_PlaylistFiles_PlaylistId);
            relationalModel.Tables.Add(("PlaylistFiles", null), playlistFilesTable);
            var playlistFilesTableMapping = new TableMapping(playlistFileEntity, playlistFilesTable, true);
            playlistFilesTable.AddTypeMapping(playlistFilesTableMapping, false);
            tableMappings1.Add(playlistFilesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, playlistFileEntity.FindProperty("Id")!, playlistFilesTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn1, playlistFileEntity.FindProperty("CreatedAt")!, playlistFilesTableMapping);
            RelationalModel.CreateColumnMapping(lastOpenedAtColumn1, playlistFileEntity.FindProperty("LastOpenedAt")!, playlistFilesTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn0, playlistFileEntity.FindProperty("Path")!, playlistFilesTableMapping);
            RelationalModel.CreateColumnMapping(playlistIdColumn, playlistFileEntity.FindProperty("PlaylistId")!, playlistFilesTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn1, playlistFileEntity.FindProperty("UpdatedAt")!, playlistFilesTableMapping);

            var privateEntity = FindEntityType("IOApp.Features.PrivateEntity")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            privateEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var ioAppPrivateEntityTableBase = new TableBase("IOApp.Features.PrivateEntity", null, relationalModel);
            var createdAtColumnBase2 = new ColumnBase<ColumnMappingBase>("CreatedAt", "INTEGER", ioAppPrivateEntityTableBase);
            ioAppPrivateEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase2);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", ioAppPrivateEntityTableBase);
            ioAppPrivateEntityTableBase.Columns.Add("Id", idColumnBase2);
            var lastOpenedAtColumnBase2 = new ColumnBase<ColumnMappingBase>("LastOpenedAt", "INTEGER", ioAppPrivateEntityTableBase);
            ioAppPrivateEntityTableBase.Columns.Add("LastOpenedAt", lastOpenedAtColumnBase2);
            var pathColumnBase1 = new ColumnBase<ColumnMappingBase>("Path", "TEXT", ioAppPrivateEntityTableBase)
            {
                IsNullable = true
            };
            ioAppPrivateEntityTableBase.Columns.Add("Path", pathColumnBase1);
            var updatedAtColumnBase2 = new ColumnBase<ColumnMappingBase>("UpdatedAt", "INTEGER", ioAppPrivateEntityTableBase);
            ioAppPrivateEntityTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase2);
            relationalModel.DefaultTables.Add("IOApp.Features.PrivateEntity", ioAppPrivateEntityTableBase);
            var ioAppPrivateEntityMappingBase = new TableMappingBase<ColumnMappingBase>(privateEntity, ioAppPrivateEntityTableBase, true);
            ioAppPrivateEntityTableBase.AddTypeMapping(ioAppPrivateEntityMappingBase, false);
            defaultTableMappings2.Add(ioAppPrivateEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, privateEntity.FindProperty("Id")!, ioAppPrivateEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase2, privateEntity.FindProperty("CreatedAt")!, ioAppPrivateEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastOpenedAtColumnBase2, privateEntity.FindProperty("LastOpenedAt")!, ioAppPrivateEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase1, privateEntity.FindProperty("Path")!, ioAppPrivateEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase2, privateEntity.FindProperty("UpdatedAt")!, ioAppPrivateEntityMappingBase);

            var tableMappings2 = new List<TableMapping>();
            privateEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var privateTable = new Table("Private", null, relationalModel);
            var idColumn2 = new Column("Id", "INTEGER", privateTable);
            privateTable.Columns.Add("Id", idColumn2);
            var createdAtColumn2 = new Column("CreatedAt", "INTEGER", privateTable);
            privateTable.Columns.Add("CreatedAt", createdAtColumn2);
            var lastOpenedAtColumn2 = new Column("LastOpenedAt", "INTEGER", privateTable);
            privateTable.Columns.Add("LastOpenedAt", lastOpenedAtColumn2);
            var pathColumn1 = new Column("Path", "TEXT", privateTable)
            {
                IsNullable = true
            };
            privateTable.Columns.Add("Path", pathColumn1);
            var updatedAtColumn2 = new Column("UpdatedAt", "INTEGER", privateTable);
            privateTable.Columns.Add("UpdatedAt", updatedAtColumn2);
            var pK_Private = new UniqueConstraint("PK_Private", privateTable, new[] { idColumn2 });
            privateTable.PrimaryKey = pK_Private;
            var pK_PrivateUc = RelationalModel.GetKey(this,
                "IOApp.Features.PrivateEntity",
                new[] { "Id" });
            pK_Private.MappedKeys.Add(pK_PrivateUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_PrivateUc).Add(pK_Private);
            privateTable.UniqueConstraints.Add("PK_Private", pK_Private);
            relationalModel.Tables.Add(("Private", null), privateTable);
            var privateTableMapping = new TableMapping(privateEntity, privateTable, true);
            privateTable.AddTypeMapping(privateTableMapping, false);
            tableMappings2.Add(privateTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, privateEntity.FindProperty("Id")!, privateTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn2, privateEntity.FindProperty("CreatedAt")!, privateTableMapping);
            RelationalModel.CreateColumnMapping(lastOpenedAtColumn2, privateEntity.FindProperty("LastOpenedAt")!, privateTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn1, privateEntity.FindProperty("Path")!, privateTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn2, privateEntity.FindProperty("UpdatedAt")!, privateTableMapping);

            var recentEntity = FindEntityType("IOApp.Features.RecentEntity")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            recentEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var ioAppRecentEntityTableBase = new TableBase("IOApp.Features.RecentEntity", null, relationalModel);
            var createdAtColumnBase3 = new ColumnBase<ColumnMappingBase>("CreatedAt", "INTEGER", ioAppRecentEntityTableBase);
            ioAppRecentEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase3);
            var idColumnBase3 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", ioAppRecentEntityTableBase);
            ioAppRecentEntityTableBase.Columns.Add("Id", idColumnBase3);
            var lastOpenedAtColumnBase3 = new ColumnBase<ColumnMappingBase>("LastOpenedAt", "INTEGER", ioAppRecentEntityTableBase);
            ioAppRecentEntityTableBase.Columns.Add("LastOpenedAt", lastOpenedAtColumnBase3);
            var pathColumnBase2 = new ColumnBase<ColumnMappingBase>("Path", "TEXT", ioAppRecentEntityTableBase)
            {
                IsNullable = true
            };
            ioAppRecentEntityTableBase.Columns.Add("Path", pathColumnBase2);
            var updatedAtColumnBase3 = new ColumnBase<ColumnMappingBase>("UpdatedAt", "INTEGER", ioAppRecentEntityTableBase);
            ioAppRecentEntityTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase3);
            relationalModel.DefaultTables.Add("IOApp.Features.RecentEntity", ioAppRecentEntityTableBase);
            var ioAppRecentEntityMappingBase = new TableMappingBase<ColumnMappingBase>(recentEntity, ioAppRecentEntityTableBase, true);
            ioAppRecentEntityTableBase.AddTypeMapping(ioAppRecentEntityMappingBase, false);
            defaultTableMappings3.Add(ioAppRecentEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase3, recentEntity.FindProperty("Id")!, ioAppRecentEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase3, recentEntity.FindProperty("CreatedAt")!, ioAppRecentEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastOpenedAtColumnBase3, recentEntity.FindProperty("LastOpenedAt")!, ioAppRecentEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase2, recentEntity.FindProperty("Path")!, ioAppRecentEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase3, recentEntity.FindProperty("UpdatedAt")!, ioAppRecentEntityMappingBase);

            var tableMappings3 = new List<TableMapping>();
            recentEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var recentTable = new Table("Recent", null, relationalModel);
            var idColumn3 = new Column("Id", "INTEGER", recentTable);
            recentTable.Columns.Add("Id", idColumn3);
            var createdAtColumn3 = new Column("CreatedAt", "INTEGER", recentTable);
            recentTable.Columns.Add("CreatedAt", createdAtColumn3);
            var lastOpenedAtColumn3 = new Column("LastOpenedAt", "INTEGER", recentTable);
            recentTable.Columns.Add("LastOpenedAt", lastOpenedAtColumn3);
            var pathColumn2 = new Column("Path", "TEXT", recentTable)
            {
                IsNullable = true
            };
            recentTable.Columns.Add("Path", pathColumn2);
            var updatedAtColumn3 = new Column("UpdatedAt", "INTEGER", recentTable);
            recentTable.Columns.Add("UpdatedAt", updatedAtColumn3);
            var pK_Recent = new UniqueConstraint("PK_Recent", recentTable, new[] { idColumn3 });
            recentTable.PrimaryKey = pK_Recent;
            var pK_RecentUc = RelationalModel.GetKey(this,
                "IOApp.Features.RecentEntity",
                new[] { "Id" });
            pK_Recent.MappedKeys.Add(pK_RecentUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_RecentUc).Add(pK_Recent);
            recentTable.UniqueConstraints.Add("PK_Recent", pK_Recent);
            relationalModel.Tables.Add(("Recent", null), recentTable);
            var recentTableMapping = new TableMapping(recentEntity, recentTable, true);
            recentTable.AddTypeMapping(recentTableMapping, false);
            tableMappings3.Add(recentTableMapping);
            RelationalModel.CreateColumnMapping(idColumn3, recentEntity.FindProperty("Id")!, recentTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn3, recentEntity.FindProperty("CreatedAt")!, recentTableMapping);
            RelationalModel.CreateColumnMapping(lastOpenedAtColumn3, recentEntity.FindProperty("LastOpenedAt")!, recentTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn2, recentEntity.FindProperty("Path")!, recentTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn3, recentEntity.FindProperty("UpdatedAt")!, recentTableMapping);
            var fK_PlaylistFiles_Playlists_PlaylistId = new ForeignKeyConstraint(
                "FK_PlaylistFiles_Playlists_PlaylistId", playlistFilesTable, playlistsTable,
                new[] { playlistIdColumn },
                playlistsTable.FindUniqueConstraint("PK_Playlists")!, ReferentialAction.Cascade);
            var fK_PlaylistFiles_Playlists_PlaylistIdFk = RelationalModel.GetForeignKey(this,
                "IOApp.Features.PlaylistFileEntity",
                new[] { "PlaylistId" },
                "IOApp.Features.PlaylistEntity",
                new[] { "Id" });
            fK_PlaylistFiles_Playlists_PlaylistId.MappedForeignKeys.Add(fK_PlaylistFiles_Playlists_PlaylistIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_PlaylistFiles_Playlists_PlaylistIdFk).Add(fK_PlaylistFiles_Playlists_PlaylistId);
            playlistFilesTable.ForeignKeyConstraints.Add(fK_PlaylistFiles_Playlists_PlaylistId);
            playlistsTable.ReferencingForeignKeyConstraints.Add(fK_PlaylistFiles_Playlists_PlaylistId);
            return relationalModel.MakeReadOnly();
        }
    }
}
