// <auto-generated />
using IOApp.Features;
using IOCore.Files;
using IOData;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Reflection;
using static IOApp.Features.SecureFileItem;

#pragma warning disable 219, 612, 618
#nullable disable

namespace IOApp.CompiledModels
{
    internal partial class FileEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "IOApp.Features.FileEntity",
                typeof(FileEntity),
                baseEntityType);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(CoreEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CoreEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                keyComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var censorType = runtimeEntityType.AddProperty(
                "CensorType",
                typeof(CensorType),
                propertyInfo: typeof(FileEntity).GetProperty("CensorType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<CensorType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            censorType.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<CensorType>(
                    (CensorType v1, CensorType v2) => object.Equals((object)v1, (object)v2),
                    (CensorType v) => v.GetHashCode(),
                    (CensorType v) => v),
                keyComparer: new ValueComparer<CensorType>(
                    (CensorType v1, CensorType v2) => object.Equals((object)v1, (object)v2),
                    (CensorType v) => v.GetHashCode(),
                    (CensorType v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<CensorType, int>(
                    (CensorType value) => (int)value,
                    (int value) => (CensorType)value),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<CensorType, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<CensorType, int>(
                        (CensorType value) => (int)value,
                        (int value) => (CensorType)value)));
            censorType.SetSentinelFromProviderValue(0);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(ulong),
                propertyInfo: typeof(CoreEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CoreEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0ul);
            createdAt.TypeMapping = SqliteULongTypeMapping.Default;

            var fileType = runtimeEntityType.AddProperty(
                "FileType",
                typeof(ZFile.FileType),
                propertyInfo: typeof(FileEntity).GetProperty("FileType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<FileType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            fileType.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<ZFile.FileType>(
                    (ZFile.FileType v1, ZFile.FileType v2) => object.Equals((object)v1, (object)v2),
                    (ZFile.FileType v) => v.GetHashCode(),
                    (ZFile.FileType v) => v),
                keyComparer: new ValueComparer<ZFile.FileType>(
                    (ZFile.FileType v1, ZFile.FileType v2) => object.Equals((object)v1, (object)v2),
                    (ZFile.FileType v) => v.GetHashCode(),
                    (ZFile.FileType v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"),
                converter: new ValueConverter<ZFile.FileType, int>(
                    (ZFile.FileType value) => (int)value,
                    (int value) => (ZFile.FileType)value),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ZFile.FileType, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<ZFile.FileType, int>(
                        (ZFile.FileType value) => (int)value,
                        (int value) => (ZFile.FileType)value)));
            fileType.SetSentinelFromProviderValue(0);

            var isFavorite = runtimeEntityType.AddProperty(
                "IsFavorite",
                typeof(bool),
                propertyInfo: typeof(FileEntity).GetProperty("IsFavorite", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<IsFavorite>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isFavorite.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    (bool v1, bool v2) => v1 == v2,
                    (bool v) => v.GetHashCode(),
                    (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    (bool v1, bool v2) => v1 == v2,
                    (bool v) => v.GetHashCode(),
                    (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    (bool v1, bool v2) => v1 == v2,
                    (bool v) => v.GetHashCode(),
                    (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var lastOpenedAt = runtimeEntityType.AddProperty(
                "LastOpenedAt",
                typeof(ulong),
                propertyInfo: typeof(CoreEntity).GetProperty("LastOpenedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CoreEntity).GetField("<LastOpenedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0ul);
            lastOpenedAt.TypeMapping = SqliteULongTypeMapping.Default;

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            note.TypeMapping = SqliteStringTypeMapping.Default;

            var path = runtimeEntityType.AddProperty(
                "Path",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Path", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Path>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            path.TypeMapping = SqliteStringTypeMapping.Default;

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(ulong),
                propertyInfo: typeof(CoreEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CoreEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0ul);
            updatedAt.TypeMapping = SqliteULongTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Files");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
