// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace IOApp.CompiledModels
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var fileEntity = FileEntityEntityType.Create(this);

            FileEntityEntityType.CreateAnnotations(fileEntity);

            AddAnnotation("ProductVersion", "8.0.5");
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var fileEntity = FindEntityType("IOApp.Features.SecuredFileEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            fileEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var iOAppFeaturesFileEntityTableBase = new TableBase("IOApp.Features.SecuredFileEntity", null, relationalModel);
            var censorTypeColumnBase = new ColumnBase<ColumnMappingBase>("CensorType", "INTEGER", iOAppFeaturesFileEntityTableBase);
            iOAppFeaturesFileEntityTableBase.Columns.Add("CensorType", censorTypeColumnBase);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "INTEGER", iOAppFeaturesFileEntityTableBase);
            iOAppFeaturesFileEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var fileTypeColumnBase = new ColumnBase<ColumnMappingBase>("FileType", "INTEGER", iOAppFeaturesFileEntityTableBase);
            iOAppFeaturesFileEntityTableBase.Columns.Add("FileType", fileTypeColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", iOAppFeaturesFileEntityTableBase);
            iOAppFeaturesFileEntityTableBase.Columns.Add("Id", idColumnBase);
            var isFavoriteColumnBase = new ColumnBase<ColumnMappingBase>("IsFavorite", "INTEGER", iOAppFeaturesFileEntityTableBase);
            iOAppFeaturesFileEntityTableBase.Columns.Add("IsFavorite", isFavoriteColumnBase);
            var lastOpenedAtColumnBase = new ColumnBase<ColumnMappingBase>("LastOpenedAt", "INTEGER", iOAppFeaturesFileEntityTableBase);
            iOAppFeaturesFileEntityTableBase.Columns.Add("LastOpenedAt", lastOpenedAtColumnBase);
            var noteColumnBase = new ColumnBase<ColumnMappingBase>("Note", "TEXT", iOAppFeaturesFileEntityTableBase)
            {
                IsNullable = true
            };
            iOAppFeaturesFileEntityTableBase.Columns.Add("Note", noteColumnBase);
            var pathColumnBase = new ColumnBase<ColumnMappingBase>("Path", "TEXT", iOAppFeaturesFileEntityTableBase)
            {
                IsNullable = true
            };
            iOAppFeaturesFileEntityTableBase.Columns.Add("Path", pathColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "INTEGER", iOAppFeaturesFileEntityTableBase);
            iOAppFeaturesFileEntityTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            relationalModel.DefaultTables.Add("IOApp.Features.SecuredFileEntity", iOAppFeaturesFileEntityTableBase);
            var iOAppFeaturesFileEntityMappingBase = new TableMappingBase<ColumnMappingBase>(fileEntity, iOAppFeaturesFileEntityTableBase, true);
            iOAppFeaturesFileEntityTableBase.AddTypeMapping(iOAppFeaturesFileEntityMappingBase, false);
            defaultTableMappings.Add(iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, fileEntity.FindProperty("Id")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)censorTypeColumnBase, fileEntity.FindProperty("CensorType")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, fileEntity.FindProperty("CreatedAt")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fileTypeColumnBase, fileEntity.FindProperty("FileType")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isFavoriteColumnBase, fileEntity.FindProperty("IsFavorite")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastOpenedAtColumnBase, fileEntity.FindProperty("LastOpenedAt")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)noteColumnBase, fileEntity.FindProperty("Note")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase, fileEntity.FindProperty("Path")!, iOAppFeaturesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, fileEntity.FindProperty("UpdatedAt")!, iOAppFeaturesFileEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            fileEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var filesTable = new Table("Files", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", filesTable);
            filesTable.Columns.Add("Id", idColumn);
            var censorTypeColumn = new Column("CensorType", "INTEGER", filesTable);
            filesTable.Columns.Add("CensorType", censorTypeColumn);
            var createdAtColumn = new Column("CreatedAt", "INTEGER", filesTable);
            filesTable.Columns.Add("CreatedAt", createdAtColumn);
            var fileTypeColumn = new Column("FileType", "INTEGER", filesTable);
            filesTable.Columns.Add("FileType", fileTypeColumn);
            var isFavoriteColumn = new Column("IsFavorite", "INTEGER", filesTable);
            filesTable.Columns.Add("IsFavorite", isFavoriteColumn);
            var lastOpenedAtColumn = new Column("LastOpenedAt", "INTEGER", filesTable);
            filesTable.Columns.Add("LastOpenedAt", lastOpenedAtColumn);
            var noteColumn = new Column("Note", "TEXT", filesTable)
            {
                IsNullable = true
            };
            filesTable.Columns.Add("Note", noteColumn);
            var pathColumn = new Column("Path", "TEXT", filesTable)
            {
                IsNullable = true
            };
            filesTable.Columns.Add("Path", pathColumn);
            var updatedAtColumn = new Column("UpdatedAt", "INTEGER", filesTable);
            filesTable.Columns.Add("UpdatedAt", updatedAtColumn);
            var pK_Files = new UniqueConstraint("PK_Files", filesTable, new[] { idColumn });
            filesTable.PrimaryKey = pK_Files;
            var pK_FilesUc = RelationalModel.GetKey(this,
                "IOApp.Features.SecuredFileEntity",
                new[] { "Id" });
            pK_Files.MappedKeys.Add(pK_FilesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FilesUc).Add(pK_Files);
            filesTable.UniqueConstraints.Add("PK_Files", pK_Files);
            relationalModel.Tables.Add(("Files", null), filesTable);
            var filesTableMapping = new TableMapping(fileEntity, filesTable, true);
            filesTable.AddTypeMapping(filesTableMapping, false);
            tableMappings.Add(filesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, fileEntity.FindProperty("Id")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(censorTypeColumn, fileEntity.FindProperty("CensorType")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, fileEntity.FindProperty("CreatedAt")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(fileTypeColumn, fileEntity.FindProperty("FileType")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(isFavoriteColumn, fileEntity.FindProperty("IsFavorite")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(lastOpenedAtColumn, fileEntity.FindProperty("LastOpenedAt")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(noteColumn, fileEntity.FindProperty("Note")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn, fileEntity.FindProperty("Path")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, fileEntity.FindProperty("UpdatedAt")!, filesTableMapping);
            return relationalModel.MakeReadOnly();
        }
    }
}
